# -*- coding: utf-8 -*-
"""
Bundle data into assets/data.js for the interactive dashboard (index.html).

两种模式（merged 优先）：
  1. merged  : data/merged/*_creator_all.csv + meta.json（由 scripts/merge_all.py 产出）
               —— 多份重叠导出合并后的「全周期」单一快照，period 元数据写入 data.js
  2. weekly  : data/weeks/*_creator_weekly.csv（由 scripts/prepare.py 产出，旧周度模式）
               —— 追加新周 CSV 后重跑，dashboard 自动包含全部周

用法：
    python scripts/build_data.py
"""
import datetime as dt
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
MERGED_DIR = ROOT / "data" / "merged"
WEEKS_DIR = ROOT / "data" / "weeks"
OUT = ROOT / "assets" / "data.js"

# 字段重命名：原始导出名 -> dashboard 内部名（缩短传输体积，语义不变）
RENAME = {
    "creator_key": "creator_key",
    "Creator name": "handle",
    "week_start": "week_start",
    "Creator-attributed GMV": "gmv",
    "Creator LIVE-attributed GMV": "gmv_live",
    "Creator video-attributed GMV": "gmv_video",
    "Refunds": "refunds",
    "Attributed orders": "orders",
    "Creator-attributed items sold": "items_sold",
    "Items refunded": "items_refunded",
    "AOV": "aov",
    "Affiliate product card-attributed GMV": "card_gmv",
    "CTOR": "ctor",
    "LIVE streams": "lives",
    "Videos": "videos",
    "Total sample content": "sample_content",
    "Samples shipped": "samples",
    "Products added to showcase": "added_to_showcase",
    "CTR": "ctr",
    "Product impressions": "impressions",
    "Video views": "views",
    "Customers": "customers",
    "Products sold": "products_sold",
    "Est. commission": "commission",
    "Est. flat fee": "flat_fee",
    "sample_cost": "sample_cost",
    "content_count": "content_count",
}

FIELDS = list(RENAME.values())

INT_FIELDS = {
    "orders", "items_sold", "items_refunded", "lives", "videos",
    "sample_content", "samples", "added_to_showcase", "impressions",
    "views", "customers", "products_sold",
}


def load_frame(f: Path) -> pd.DataFrame:
    df = pd.read_csv(f)
    # 容错：上游脚本派生列若缺失则现算
    if "content_count" not in df.columns:
        df["content_count"] = df["Videos"] + df["LIVE streams"]
    if "creator_key" not in df.columns:
        df["creator_key"] = df["Creator name"].astype(str).str.strip().str.lower()
    if "sample_cost" not in df.columns:
        df["sample_cost"] = df["Samples shipped"] * 5.0
    return df


def main() -> None:
    merged_files = sorted(MERGED_DIR.glob("*_creator_all.csv"))
    meta_path = MERGED_DIR / "meta.json"
    if merged_files:
        files, mode = merged_files, "merged"
        meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else {}
    else:
        files = sorted(WEEKS_DIR.glob("*_creator_weekly.csv"))
        mode, meta = "weekly", {}
    if not files:
        raise SystemExit(f"no data found under {MERGED_DIR} or {WEEKS_DIR}")

    df = pd.concat([load_frame(f) for f in files], ignore_index=True)

    for src, dst in RENAME.items():
        if src not in df.columns:
            raise SystemExit(f"missing column: {src}")

    df = df[[c for c in RENAME if c in df.columns]].rename(columns=RENAME)

    for c in INT_FIELDS:
        df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0).astype(int)
    for c in FIELDS:
        if c not in INT_FIELDS and c not in ("creator_key", "handle", "week_start"):
            df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0.0)

    weeks = sorted(df["week_start"].astype(str).unique().tolist())
    rows = df[FIELDS].values.tolist()

    payload = {
        "updated": pd.Timestamp("today").strftime("%Y-%m-%d"),
        "unit_sample_cost": float(df["sample_cost"].sum())
        / max(int(df["samples"].sum()), 1),
        "mode": mode,
        "weeks": weeks,
        "fields": FIELDS,
        "rows": rows,
    }
    if mode == "merged" and meta:
        raw = int(meta.get("raw_rows", len(df)))
        payload["period"] = {
            "from": meta.get("period_from", weeks[0]),
            "to": dt.date.today().isoformat(),
            "sources": len(meta.get("sources", [])),
            "rawRows": raw,
            "dedup": raw - int(meta.get("union_creators", len(df))),
        }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    src_note = ("merged from data/merged/*_creator_all.csv (scripts/merge_all.py)"
                if mode == "merged" else
                "weekly appended data/weeks/*_creator_weekly.csv")
    OUT.write_text(
        "/* Auto-generated by scripts/build_data.py — do not edit by hand.\n"
        "   Source: " + src_note + " */\n"
        "globalThis.DATA = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )

    print(f"mode    : {mode}")
    print(f"periods : {weeks}")
    if mode == "merged":
        print(f"period  : {payload['period']['from']} → {payload['period']['to']}"
              f" ({payload['period']['sources']} 份导出, raw {payload['period']['rawRows']}"
              f" → union {len(rows)})")
    print(f"rows    : {len(rows)}")
    print(f"written : {OUT} ({OUT.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
