# -*- coding: utf-8 -*-
"""
Bundle weekly CSVs (data/weeks/*_creator_weekly.csv) into assets/data.js
for the interactive dashboard (index.html).

用法：
    python scripts/build_data.py            # 读取 data/weeks/*.csv -> assets/data.js

每周追加新的 *_creator_weekly.csv 后重跑一次，dashboard 即自动包含全部周。
"""

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
WEEKS_DIR = ROOT / "data" / "weeks"
OUT = ROOT / "assets" / "data.js"

# 字段重命名：原始导出名 -> dashboard 内部名（缩短传输体积，语义不变）
RENAME = {
    "creator_key": "creator_key",
    "Creator name": "handle",
    "week_start": "week_start",
    "Creator-attributed GMV": "gmv",
    "Creator LIVE-attributed GMV": "gmv_live",
    "Creator video-attributed GMV": "gmv_video",
    "Refunds": "refunds",
    "Attributed orders": "orders",
    "Creator-attributed items sold": "items_sold",
    "Items refunded": "items_refunded",
    "AOV": "aov",
    "Affiliate product card-attributed GMV": "card_gmv",
    "CTOR": "ctor",
    "LIVE streams": "lives",
    "Videos": "videos",
    "Total sample content": "sample_content",
    "Samples shipped": "samples",
    "Products added to showcase": "added_to_showcase",
    "CTR": "ctr",
    "Product impressions": "impressions",
    "Video views": "views",
    "Customers": "customers",
    "Products sold": "products_sold",
    "Est. commission": "commission",
    "Est. flat fee": "flat_fee",
    "sample_cost": "sample_cost",
    "content_count": "content_count",
}

FIELDS = list(RENAME.values())

INT_FIELDS = {
    "orders", "items_sold", "items_refunded", "lives", "videos",
    "sample_content", "samples", "added_to_showcase", "impressions",
    "views", "customers", "products_sold",
}


def main() -> None:
    files = sorted(WEEKS_DIR.glob("*_creator_weekly.csv"))
    if not files:
        raise SystemExit(f"no *_creator_weekly.csv found under {WEEKS_DIR}")

    frames = []
    for f in files:
        df = pd.read_csv(f)
        # 容错：prepare.py 生成的派生列若缺失则现算
        if "content_count" not in df.columns:
            df["content_count"] = df["Videos"] + df["LIVE streams"]
        if "creator_key" not in df.columns:
            df["creator_key"] = df["Creator name"].astype(str).str.strip().str.lower()
        if "sample_cost" not in df.columns:
            df["sample_cost"] = df["Samples shipped"] * 5.0
        frames.append(df)

    df = pd.concat(frames, ignore_index=True)

    for src, dst in RENAME.items():
        if src not in df.columns and src != dst:
            raise SystemExit(f"missing column: {src}")

    df = df[[c for c in RENAME if c in df.columns]].rename(columns=RENAME)

    for c in INT_FIELDS:
        df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0).astype(int)
    for c in FIELDS:
        if c not in INT_FIELDS and c not in ("creator_key", "handle", "week_start"):
            df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0.0)

    weeks = sorted(df["week_start"].unique().tolist())
    rows = df[FIELDS].values.tolist()

    payload = {
        "updated": pd.Timestamp("today").strftime("%Y-%m-%d"),
        "unit_sample_cost": float(df["sample_cost"].sum())
        / max(int(df["samples"].sum()), 1),
        "weeks": weeks,
        "fields": FIELDS,
        "rows": rows,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "/* Auto-generated by scripts/build_data.py — do not edit by hand.\n"
        "   Source: data/weeks/*_creator_weekly.csv (weekly appended). */\n"
        "globalThis.DATA = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )

    print(f"weeks   : {len(weeks)} -> {weeks}")
    print(f"rows    : {len(rows)}")
    print(f"written : {OUT} ({OUT.stat().st_size/1024:.1f} KB)")


if __name__ == "__main__":
    main()
